INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (99, 123.45, 'gabo');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (100, 1.0, 'gabo');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (101, 150.0, 'gabo');